version: '3'
services:
  universer:
    restart: always
    container_name: universer
    image: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com/univer/universer:latest
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - ./universer-configs:/data/configs
    depends_on:
      - univer-postgres
      - univer-rabbitmq
      - univer-clickhouse

  collaboration-server:
    restart: always
    container_name: collaboration-server
    image: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com/univer/univer-collaboration:latest
    environment:
      - URL_OF_TRANSFORM_SERVICE=0.0.0.0:5001
      - URL_OF_APPLY_SERVICE=0.0.0.0:5002
      - URL_OF_UNIVERSER_SERVICE=universer:8000
      - URL_OF_SNAPSHOT_SERVICE=universer:9000
      - SAVE_SNAPSHOT_INTERVAL=3
    ports:
      - 5001:5001
      - 5002:5002

  collaboration-demo:
    image: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com/univer/univer-collaboration-demo:latest
    ports:
      - "3010:3010"

  univer-postgres:
    image: postgres:latest
    restart: always
    container_name: univer-postgres
    environment:
      - POSTGRES_DB=univer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - /mnt/postgresql:/var/lib/postgresql/data/:rw
      - ./sql/postgresql:/docker-entrypoint-initdb.d

  univer-rabbitmq:
    restart: always
    container_name: univer-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "8090:15672"
      - "5672:5672"

  univer-clickhouse:
    restart: always
    container_name: univer-clickhouse
    image: bitnami/clickhouse:23.10.2-debian-11-r0
    environment:
      - CLICKHOUSE_ADMIN_USER=clickhouse
      - CLICKHOUSE_ADMIN_PASSWORD=clickhouse
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - clickhouse-data:/bitnami/clickhouse
      - ./sql/clickhouse:/docker-entrypoint-initdb.d
    ports:
      - "4000:8123"
      - "4001:9000"

volumes:

  clickhouse-data:
