name: Main Workflow

on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    

jobs:
  deploy:
    name: DockerComposeDeploy
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@v1.0.0
      env:
        REGISTRY_USERNAME: "${{ secrets.REGISTRY_USERNAME }}"
        REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ vars.PORT }}
        script_stop: true
        envs: REGISTRY_USERNAME,REGISTRY_PASSWORD
        script: |
          local_dir=~/helm-charts;

          repo_url="https://github.com/dream-num/helm-charts.git";

          if [ ! -d "$local_dir" ]; then \
            source ~/.bashrc && env && git clone "$repo_url" $local_dir; \
          else \
            cd $local_dir; \
            source ~/.bashrc && env && git pull; \
          fi;

          ls $local_dir/docker-compose;

          cd $local_dir/docker-compose;
          bash run.dev.sh;

          exit;


